POST http://localhost:8080/books/addBook
Content-Type: application/json

{
  "isbn": "9780132350884",
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "publisher": "Pearson Education",
  "type": "Educational"
}

###
DELETE http://localhost:8080/books/removeBook/5

###
GET http://localhost:8080/books/getAllBooks

###
GET http://localhost:8080/books/getBook/2

###
PUT http://localhost:8080/books/updateBook
Content-Type: application/json

{
  "id": 6,
  "isbn": "9780739360385",
  "title": "Harry Potter & Deathly Hollows",
  "author": "J. K. Rowling",
  "publisher": "Bloomsbury Pub Limited",
  "type": "Fantasy Fiction"
}

###


